language: php

sudo: false

php:
  - 5.5
  - 5.6

env:
  matrix:
    - PREFER_LOWEST=""
    - PREFER_LOWEST="--prefer-lowest"

install:
  - composer update --prefer-source $PREFER_LOWEST

script:
  - vendor/bin/phpunit